# Build settings
title: "My IPTVs"
theme: minima
minima:
  date_format: "%b %-d, %Y"
  skin: dark
plugins:
  - jekyll-last-modified-at

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%d-%b-%y'
    
